-- Personal Ava: Jared's own AI assistant, separate from RoofGuard (Spark, 2026-10-04).
-- Jared: "build a separate Ava for /admin ... I want RoofGuard to be separate ... if RoofGuard's owners want to buy that
-- portion we need to split it off." Everything personal lives in ava_* and edge fn ava-assistant; everything RoofGuard
-- stays in rg_* and roofguard-*. Her line: (816) 429-9495 (moved off RoofGuard; nobody but test contacts ever had it).
-- People can call her any time: she takes a message and Jared gets it as a Scout push.

create table if not exists public.ava_settings (
  id boolean primary key default true check (id),
  agent_id text, phone_number_id text, from_number text not null default '+18164299495',
  voice_id text not null default 'pFZP5JQG7iQjIQuC4Bku',      -- Lily
  llm text not null default 'gemini-2.5-flash-lite',
  webhook_id text, telnyx_ovp_id text, telnyx_out_connection_id text, telnyx_in_connection_id text,
  cost_voice_per_min numeric not null default 0.08, cost_phone_per_min numeric not null default 0.007,
  setup_log jsonb not null default '[]'::jsonb, updated_at timestamptz not null default now()
);
insert into public.ava_settings (id) values (true) on conflict do nothing;

create table if not exists public.ava_contacts (
  id uuid primary key default gen_random_uuid(),
  name text not null, phone text unique, relationship text, notes text,
  created_at timestamptz not null default now()
);
insert into public.ava_contacts (name, phone, relationship, notes)
values ('Mom', '+18168203760', 'mother', 'Jared''s mom. Warm and chatty. She can call Ava any time to leave Jared a message.')
on conflict (phone) do nothing;

create table if not exists public.ava_calls (
  id uuid primary key default gen_random_uuid(),
  direction text not null check (direction in ('inbound', 'outbound')),
  phone text,                                   -- the other person's number
  contact_id uuid references public.ava_contacts(id) on delete set null,
  caller_name text,                             -- what they said their name was (inbound) or who we called
  purpose text,                                 -- outbound: why Jared asked Ava to call
  conversation_id text unique,
  status text not null default 'queued' check (status in ('queued', 'in_progress', 'completed', 'failed')),
  summary text, message text,                   -- message for Jared, if they left one
  urgent boolean not null default false, callback_wanted boolean not null default false,
  duration_sec int, transcript jsonb, llm_cost numeric,
  read_at timestamptz,                          -- Jared opened it in /admin/ava
  created_at timestamptz not null default now(), ended_at timestamptz
);
create index if not exists ava_calls_recent on public.ava_calls (created_at desc);

alter table public.ava_settings enable row level security;
alter table public.ava_contacts enable row level security;
alter table public.ava_calls enable row level security;
create policy "admin ava_settings" on public.ava_settings for all to authenticated using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));
create policy "admin ava_contacts" on public.ava_contacts for all to authenticated using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));
create policy "admin ava_calls" on public.ava_calls for all to authenticated using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));
grant select, insert, update, delete on public.ava_settings, public.ava_contacts, public.ava_calls to authenticated;

-- Vault access for the ava-assistant function only (service role). Shares Jared's ElevenLabs + Telnyx keys.
create or replace function public.ava_secret(p_name text)
returns text language plpgsql stable security definer set search_path = public, vault as $$
begin
  if p_name not in ('elevenlabs_api_key', 'telnyx_api_key', 'ava_webhook_secret', 'ava_sip_password', 'ava_init_secret') then
    raise exception 'ava_secret: % is not an Ava secret', p_name;
  end if;
  return (select decrypted_secret from vault.decrypted_secrets where name = p_name limit 1);
end $$;
create or replace function public.ava_secret_put(p_name text, p_value text)
returns void language plpgsql security definer set search_path = public, vault as $$
declare v_id uuid;
begin
  if p_name not in ('ava_webhook_secret', 'ava_sip_password', 'ava_init_secret') then raise exception 'ava_secret_put: % not allowed', p_name; end if;
  select id into v_id from vault.secrets where name = p_name;
  if v_id is null then perform vault.create_secret(p_value, p_name, 'Ava assistant: generated by setup');
  else perform vault.update_secret(v_id, p_value); end if;
end $$;
revoke execute on function public.ava_secret(text), public.ava_secret_put(text, text) from public, anon, authenticated;

-- Admin actions from /admin/ava go through this (same pattern as rg_caller_action)
create or replace function public.ava_action(p_action text)
returns bigint language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role(auth.uid(), 'admin') then raise exception 'admin only'; end if;
  if p_action not in ('setup') then raise exception 'unknown action %', p_action; end if;
  return invoke_edge_function('ava-assistant', jsonb_build_object('action', p_action), 150000);
end $$;
revoke execute on function public.ava_action(text) from public, anon;
grant execute on function public.ava_action(text) to authenticated;

-- What she's cost (personal side only)
create or replace function public.ava_costs()
returns jsonb language sql stable security definer set search_path = public as $$
  select case when not public.has_role(auth.uid(), 'admin') then null else jsonb_build_object(
    'total', round(coalesce(sum(coalesce(c.duration_sec, 0) / 60.0 * s.cost_voice_per_min + ceil(coalesce(c.duration_sec, 0) / 60.0) * s.cost_phone_per_min + coalesce(c.llm_cost, 0)), 0)
                   + 1.00 * (1 + extract(month from age(now(), date '2026-10-04'))::int + 12 * extract(year from age(now(), date '2026-10-04'))::int), 2),
    'month', round(coalesce(sum(coalesce(c.duration_sec, 0) / 60.0 * s.cost_voice_per_min + ceil(coalesce(c.duration_sec, 0) / 60.0) * s.cost_phone_per_min + coalesce(c.llm_cost, 0))
                   filter (where date_trunc('month', c.created_at) = date_trunc('month', now())), 0), 2),
    'minutes', round(coalesce(sum(c.duration_sec), 0) / 60.0, 1), 'calls', count(c.id),
    'unread', count(c.id) filter (where c.message is not null and c.read_at is null)) end
  from ava_settings s left join ava_calls c on true
  group by s.cost_voice_per_min, s.cost_phone_per_min
$$;
revoke execute on function public.ava_costs() from public, anon;
grant execute on function public.ava_costs() to authenticated;

-- Watchdog: calls that never reported back get closed, and a broken setup is raised to Scout. Every 10 minutes.
create or replace function public.ava_watch()
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_stuck int; s ava_settings;
begin
  select * into s from ava_settings where id;
  with x as (update ava_calls set status = 'failed', summary = coalesce(summary, '[watchdog: no report after 30 min]')
              where status in ('queued', 'in_progress') and created_at < now() - interval '30 minutes' returning id)
  select count(*) into v_stuck from x;
  if s.agent_id is null or s.phone_number_id is null then
    perform bestly_raise('ava.assistant', 'problem', 'warning', 'Ava (personal) is not answering her line',
      'Her voice agent or phone number is not set up. Open /admin/ava and run Setup.', 'ava', null, true);
  elsif v_stuck >= 3 then
    perform bestly_raise('ava.assistant', 'problem', 'warning', 'Ava (personal) calls not reporting back',
      format('%s calls never got a post-call report. Check the Ava webhook in ElevenLabs.', v_stuck), 'ava', null, true);
  else
    perform bestly_raise('ava.assistant', 'resolved', 'info', 'Ava (personal) healthy', null, 'ava');
  end if;
  return jsonb_build_object('stuck_fixed', v_stuck);
end $$;
revoke execute on function public.ava_watch() from public, anon, authenticated;
select cron.schedule('ava-watch', '*/10 * * * *', $$ select public.ava_watch(); $$);
