-- Ava answers both lines (Spark, 2026-10-04). Plan: docs/ava-inbound-opusplan.md. Phases 1 and 2: storage.
-- Nothing here changes RoofGuard's hard rules, the AI disclosure, do-not-call handling or the Eli callback hold.
--
--   ava_knowledge     the ONLY thing either Ava may draw on to help a caller (curated, shareable facts)
--   ava_followups     call-backs the Avas propose after a message; nothing dials until Jared taps (shared, keyed by source)
--   ava_line_health   last result of the line watchdog per Ava
--   rg_calls          gains the message fields so RoofGuard can store incoming calls and call-backs
--   rg_settings       gains the inbound placeholder lead + the inbound Telnyx connection id
-- Shared tables (ava_knowledge, ava_followups, ava_reply_incidents, ava_line_health) are keyed by source/scope so a
-- buyer of RoofGuard copies only the roofguard rows.

-- 1. Vault allowlists: the RoofGuard init-webhook secret
create or replace function public.ava_secret(p_name text)
returns text language plpgsql stable security definer set search_path = public, vault as $$
begin
  if p_name not in ('elevenlabs_api_key', 'telnyx_api_key', 'ava_webhook_secret', 'ava_sip_password', 'ava_init_secret', 'rg_init_secret') then
    raise exception 'ava_secret: % is not an Ava secret', p_name;
  end if;
  return (select decrypted_secret from vault.decrypted_secrets where name = p_name limit 1);
end $$;
create or replace function public.ava_secret_put(p_name text, p_value text)
returns void language plpgsql security definer set search_path = public, vault as $$
declare v_id uuid;
begin
  if p_name not in ('ava_webhook_secret', 'ava_sip_password', 'ava_init_secret', 'rg_init_secret') then raise exception 'ava_secret_put: % not allowed', p_name; end if;
  select id into v_id from vault.secrets where name = p_name;
  if v_id is null then perform vault.create_secret(p_value, p_name, 'Ava assistant: generated by setup');
  else perform vault.update_secret(v_id, p_value); end if;
end $$;
create or replace function public.rg_secret(p_name text)
returns text language plpgsql stable security definer set search_path = public, vault as $$
begin
  if p_name not in ('elevenlabs_api_key', 'elevenlabs_webhook_secret', 'telnyx_api_key', 'telnyx_sip_password', 'rg_init_secret') then
    raise exception 'rg_secret: % is not a RoofGuard secret', p_name;
  end if;
  return (select decrypted_secret from vault.decrypted_secrets where name = p_name limit 1);
end $$;
create or replace function public.rg_secret_put(p_name text, p_value text)
returns void language plpgsql security definer set search_path = public, vault as $$
declare v_id uuid;
begin
  if p_name not in ('elevenlabs_webhook_secret', 'telnyx_sip_password', 'rg_init_secret') then raise exception 'rg_secret_put: % not allowed', p_name; end if;
  select id into v_id from vault.secrets where name = p_name;
  if v_id is null then perform vault.create_secret(p_value, p_name, 'RoofGuard caller: generated by setup');
  else perform vault.update_secret(v_id, p_value); end if;
end $$;

-- 2. What Ava knows. Edge functions read ONLY `where active` rows from here (plus the caller's own contact / lead row).
create table if not exists public.ava_knowledge (
  id uuid primary key default gen_random_uuid(),
  scope text not null check (scope in ('personal', 'roofguard', 'both')),
  topic text not null,
  fact text not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists ava_knowledge_scope on public.ava_knowledge (scope, active);
alter table public.ava_knowledge enable row level security;
create policy "admin ava_knowledge" on public.ava_knowledge for all to authenticated
  using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));
grant select, insert, update, delete on public.ava_knowledge to authenticated;
create or replace function public.ava_knowledge_touch() returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;
create trigger ava_knowledge_touch before update on public.ava_knowledge for each row execute function public.ava_knowledge_touch();

insert into public.ava_knowledge (scope, topic, fact)
select v.scope, v.topic, v.fact from (values
  ('personal', 'Who Jared is',    'Jared Best runs Bestly LLC, a privacy-first product studio. The website is bestly.tech.'),
  ('personal', 'Ava',             'Ava is Jared''s AI assistant. She handles his calls and messages.'),
  ('personal', 'Business inquiries', 'For business inquiries, Ava takes a message and Jared follows up. She does not discuss details or pricing.'),
  ('personal', 'InventoryProof',  'InventoryProof is a home inventory app: walk through your home and get an insurance-ready inventory report in minutes. It is on the App Store.'),
  ('personal', 'Cookie Yeti',     'Cookie Yeti dismisses cookie banners instantly so browsing is cleaner, faster and more private. It is a browser extension and a Safari and iOS app.'),
  ('personal', 'In-House Cloud',  'In-House Cloud is a private cloud Bestly sets up for a business, so its files, calls and forms live on a server the business owns. Details are on bestly.tech.'),
  ('roofguard', 'RoofGuard',      'RoofGuard is a commercial roof maintenance program run by Legacy Building Maintenance Company.'),
  ('roofguard', 'Who runs it',    'Eli Cooper runs the RoofGuard program.'),
  ('roofguard', 'How it works',   'One predictable monthly cost keeps a commercial roof on a documented maintenance schedule. It works alongside the building''s own roofer.'),
  ('roofguard', 'Pricing',        'Pricing is per square foot per month, scoped to the buildings. Ava never gives a number. Eli gives the exact figure after a free assessment.'),
  ('roofguard', 'Next step',      'The easiest next step is a free 20-minute call with Eli Cooper, who looks at the buildings and gives a per-facility figure, no obligation.'),
  ('roofguard', 'Not insurance',  'RoofGuard is a maintenance service agreement, not insurance. It works alongside a building''s insurance.'),
  ('roofguard', 'Warranties',     'Many commercial roof warranties only hold when maintenance is documented, which most owners never keep up with. RoofGuard keeps that record.')
) as v(scope, topic, fact)
where not exists (select 1 from public.ava_knowledge k where k.scope = v.scope and k.topic = v.topic);

-- 3. RoofGuard: store incoming calls and call-backs next to the outbound ones
-- direction: outbound (the dialer, as before) | inbound (someone called RoofGuard's line) | callback (Ava called them back after Jared's tap).
-- Every outbound-only report (KPIs, dial cap, opener scores) filters direction = 'outbound'.
alter table public.rg_calls add column if not exists direction text not null default 'outbound' check (direction in ('outbound', 'inbound', 'callback'));
alter table public.rg_calls add column if not exists caller_name text;
alter table public.rg_calls add column if not exists message text;
alter table public.rg_calls add column if not exists urgent boolean not null default false;
alter table public.rg_calls add column if not exists callback_wanted boolean not null default false;
alter table public.rg_calls add column if not exists callback_number text;
alter table public.rg_calls add column if not exists read_at timestamptz;
alter table public.ava_calls add column if not exists callback_number text;
create index if not exists rg_calls_direction on public.rg_calls (direction, queued_at desc) where direction <> 'outbound';

alter table public.rg_settings add column if not exists inbound_lead_id uuid references public.rg_leads(id) on delete set null;
alter table public.rg_settings add column if not exists telnyx_in_connection_id text;

-- The placeholder lead every unknown incoming caller attaches to (rg_calls.lead_id is required). No phone and marked
-- do-not-call, so the dialer can never queue it; excluded from every outbound report.
with ins as (
  insert into public.rg_leads (company, state, timezone, risk_tier, contacts, category, pitch, pitch_source, enrich_status, line_type, dnc, priority, notes)
  select 'Inbound caller (unknown)', 'CA', 'America/Los_Angeles', 'LOW', '[]'::jsonb, 'generic', '', 'category', 'not_found', 'unknown', true, 0,
         'Placeholder for calls to RoofGuard''s line from numbers that are not a known lead. Never dialed by the queue.'
  where not exists (select 1 from public.rg_leads where state = 'CA' and company = 'Inbound caller (unknown)')
  returning id)
update public.rg_settings set inbound_lead_id = coalesce((select id from ins), (select id from public.rg_leads where state = 'CA' and company = 'Inbound caller (unknown)'))
 where id and inbound_lead_id is null;

-- 4. Follow-up calls (both lines). Proposed by Ava when a caller wants a call back; dialed only after Jared taps.
create table if not exists public.ava_followups (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('ava', 'roofguard')),
  call_id uuid,                                  -- the call that asked for it (ava_calls.id or rg_calls.id)
  phone text not null,
  name text,
  reason text,
  due_at timestamptz,                            -- when it goes out (empty while proposed)
  status text not null default 'proposed' check (status in ('proposed', 'approved', 'dialing', 'done', 'dismissed')),
  result_call_id uuid,
  note text,
  reminded_at timestamptz,
  dialed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, call_id)
);
create index if not exists ava_followups_open on public.ava_followups (source, status, due_at);
alter table public.ava_followups enable row level security;
create policy "admin ava_followups" on public.ava_followups for all to authenticated
  using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));
grant select, update on public.ava_followups to authenticated;

create or replace function public.ava_calls_followup_trg() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.direction = 'inbound' and new.callback_wanted and coalesce(new.callback_number, new.phone) is not null then
    insert into ava_followups (source, call_id, phone, name, reason)
    values ('ava', new.id, coalesce(new.callback_number, new.phone), new.caller_name,
            left(coalesce(new.message, new.summary, 'Asked for a call back'), 300))
    on conflict (source, call_id) do nothing;
  end if;
  return new;
end $$;
create trigger ava_calls_followup after insert or update of callback_wanted on public.ava_calls
  for each row execute function public.ava_calls_followup_trg();

create or replace function public.rg_calls_inbound_followup_trg() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.direction = 'inbound' and new.callback_wanted and coalesce(new.callback_number, new.to_number) is not null then
    insert into ava_followups (source, call_id, phone, name, reason)
    values ('roofguard', new.id, coalesce(new.callback_number, new.to_number), new.caller_name,
            left(coalesce(new.message, new.summary, 'Asked for a call back'), 300))
    on conflict (source, call_id) do nothing;
  end if;
  return new;
end $$;
create trigger rg_calls_inbound_followup after insert or update of callback_wanted on public.rg_calls
  for each row execute function public.rg_calls_inbound_followup_trg();

-- 5. Line health (one row per Ava, written by the health action; the UI chip reads it)
create table if not exists public.ava_line_health (
  source text primary key check (source in ('ava', 'roofguard')),
  ok boolean not null,
  problems jsonb not null default '[]'::jsonb,
  healed boolean not null default false,        -- this check found a problem and the self-heal fixed it
  checked_at timestamptz not null default now(),
  last_ok_at timestamptz
);
alter table public.ava_line_health enable row level security;
create policy "admin ava_line_health" on public.ava_line_health for select to authenticated using (public.has_role(auth.uid(), 'admin'));
grant select on public.ava_line_health to authenticated;

-- 6. Reply guard: a "leak" is stored as kind 'code_leak' with leak = true (the old check constraint only knows
-- code_leak / no_hangup / repeat and cannot be changed in place). The UI shows leak = true as "Shared something sensitive".
alter table public.ava_reply_incidents add column if not exists leak boolean not null default false;
