-- RoofGuard pitch templates per lead category; {co} = company name (Spark, 2026-10-03)
create table if not exists public.rg_pitch_templates (category text primary key, body text not null, updated_at timestamptz not null default now());
alter table public.rg_pitch_templates enable row level security;
create policy rg_pitch_templates_admin on public.rg_pitch_templates for all to authenticated using (public.has_role(auth.uid(),'admin')) with check (public.has_role(auth.uid(),'admin'));
insert into public.rg_pitch_templates (category, body) values
('hospital','Under {co}''s roofs: operating rooms, imaging and life-support equipment, pharmacy stock, and patient records. One leak over a clinical area means diverted patients, cancelled procedures, mold risk, and accreditation findings. RoofGuard''s continuous scheduled maintenance keeps the envelope sealed year-round so care never stops for a roof problem.'),
('campus','Under {co}''s campus roofs: research labs and grant-funded work, libraries and archives, IT rooms, and student housing. Water over a lab or a collection can wipe out years of work, and a dorm leak displaces students overnight. RoofGuard''s continuous scheduled maintenance protects research continuity across a large, mixed-age building portfolio, before a leak becomes an institutional loss.'),
('school_district','Under {co}''s roofs: classrooms, gyms, cafeterias, technology, and thousands of students every day. A leak closes rooms or whole buildings, forces emergency repairs out of a fixed budget, and brings mold and air-quality complaints. RoofGuard''s continuous scheduled maintenance keeps every building dry on a predictable monthly cost, so roofs stop surprising the budget.'),
('government','Under {co}''s roofs: public-service counters, records, courts, IT and dispatch systems, and staff who serve residents daily. A leak can close offices, damage public records, and trigger unbudgeted emergency spending. RoofGuard''s continuous scheduled maintenance keeps public buildings dry on a predictable monthly cost, with a documented maintenance trail.'),
('airport','Under {co}''s roofs: terminals, baggage systems, IT and security screening, and concessions serving travelers around the clock. A leak over a checkpoint or baggage line backs up the whole operation. RoofGuard''s continuous scheduled maintenance keeps terminals sealed year-round so operations never pause for a roof problem.'),
('manufacturing','Under {co}''s plant roofs: production lines, controls and electrical gear, raw materials, and finished goods. One leak over a line can stop production, ruin inventory, and push back customer shipments. RoofGuard''s continuous scheduled maintenance keeps industrial roofs sealed so the line keeps running, on a predictable monthly cost.'),
('cold_food','Under {co}''s roofs: food production, refrigeration and cold storage, packaging lines, and food-safety programs. Water intrusion can contaminate product, force disposal, and create audit findings. RoofGuard''s continuous scheduled maintenance keeps the envelope sealed so product stays safe and lines stay running.'),
('pharma_cleanroom','Under {co}''s roofs: controlled cleanrooms, regulated production and lab work, and high-value inventory. A single leak can break environmental control, quarantine batches, and trigger compliance investigations. RoofGuard''s continuous scheduled maintenance protects controlled environments so validated operations never get interrupted by the roof.'),
('fab','Under {co}''s roofs: cleanrooms, precision tools, and wafer or component inventory worth millions. Any water intrusion can contaminate a cleanroom and halt output for days. RoofGuard''s continuous scheduled maintenance keeps the envelope sealed year-round so production never stops for a roof problem.'),
('data_center','Under {co}''s roofs: network and server equipment, power and cooling systems, and services customers rely on around the clock. Water near live equipment means outages, SLA penalties, and lost customer trust. RoofGuard''s continuous scheduled maintenance keeps critical facilities sealed so uptime never depends on the weather.'),
('utility','Under {co}''s roofs: control centers, substations and equipment buildings, fleet and warehouse space, and customer operations. A leak in a control or equipment building puts reliability at risk for every customer it serves. RoofGuard''s continuous scheduled maintenance keeps critical buildings sealed across a spread-out portfolio, on a predictable monthly cost.'),
('distribution','Under {co}''s roofs: racked inventory, conveyors and automation, and the fulfillment work customers depend on. Water damages stored goods and sorting equipment, stops throughput, and breaks delivery commitments. RoofGuard''s continuous scheduled maintenance protects inventory and keeps product moving.'),
('retail','Under {co}''s roofs: sales floors, inventory, refrigeration and point-of-sale systems, multiplied across every location. A leak closes a store, spoils stock, and sends customers to a competitor. RoofGuard''s continuous scheduled maintenance keeps every location open and dry on one predictable monthly cost.'),
('grocery','Under {co}''s roofs: refrigerated and frozen product, sales floors, and food-safety compliance at every store. A leak can mean spoiled inventory, health-code problems, and a closed store. RoofGuard''s continuous scheduled maintenance keeps stores dry and open, on one predictable monthly cost.'),
('restaurant','Under {co}''s roofs: kitchens, refrigeration, dining rooms, and food-safety compliance at every location. One leak can close a restaurant for the day and bring a health-inspection problem. RoofGuard''s continuous scheduled maintenance keeps locations open and dry on a predictable monthly cost.'),
('casino','Under {co}''s roofs: gaming floors, hotel rooms, restaurants, surveillance and IT systems, all running around the clock. A leak over the floor or the rooms means lost revenue by the hour and guest complaints. RoofGuard''s continuous scheduled maintenance keeps the property sealed so the floor never closes for a roof problem.'),
('hotel','Under {co}''s roofs: guest rooms, ballrooms, restaurants, and the guest experience the brand depends on. A leak takes rooms out of inventory, cancels events, and shows up in reviews. RoofGuard''s continuous scheduled maintenance keeps the property sealed so rooms stay sellable year-round.'),
('senior_living','Under {co}''s roofs: residents'' homes, care areas, medication rooms, and dining. A leak displaces vulnerable residents, invites mold, and triggers state inspection issues. RoofGuard''s continuous scheduled maintenance keeps every community dry so residents stay safe and settled.'),
('self_storage','Under {co}''s roofs: customers'' belongings, unit by unit, across a large portfolio. One leak damages tenant property, creates claims and complaints, and empties units. RoofGuard''s continuous scheduled maintenance keeps every facility dry on one predictable monthly cost.'),
('venue','Under {co}''s roof: event spaces, audio-visual and stage equipment, and the calendar of events that drives revenue. A leak can cancel events and damage expensive equipment. RoofGuard''s continuous scheduled maintenance keeps the building sealed so the calendar never gets interrupted by the roof.'),
('corporate','Under {co}''s roofs: headquarters offices, IT and server rooms, records, and the people who run the business. A leak disrupts work, damages equipment, and pulls facilities into emergency mode. RoofGuard''s continuous scheduled maintenance keeps corporate buildings dry on a predictable monthly cost, fully expensable as an operating cost.'),
('generic','Under {co}''s roofs: the people, equipment, and inventory the business runs on. A leak means downtime, damaged assets, and unplanned emergency spending. RoofGuard''s continuous scheduled maintenance keeps buildings sealed on a predictable monthly cost.')
on conflict (category) do nothing;