-- RoofGuard caller: phone provider is Telnyx, not Twilio (Jared, 2026-10-04: "as cheap as possible, but quality";
-- Telnyx lists about $0.007/min US outbound SIP vs roughly double on Twilio, $1/mo per number).
-- ElevenLabs stays the voice. Telnyx connects to it through a SIP trunk that setup creates by itself.
-- (Spark, 2026-10-04)

alter table public.rg_settings add column if not exists phone_provider text not null default 'telnyx';
alter table public.rg_settings add column if not exists telnyx_connection_id text;
alter table public.rg_settings add column if not exists telnyx_ovp_id text;

-- Keys the caller may read (service role only).
create or replace function public.rg_secret(p_name text)
returns text language plpgsql stable security definer set search_path = public, vault as $$
begin
  if p_name not in ('elevenlabs_api_key', 'elevenlabs_webhook_secret', 'telnyx_api_key', 'telnyx_sip_password') then
    raise exception 'rg_secret: % is not a RoofGuard secret', p_name;
  end if;
  return (select decrypted_secret from vault.decrypted_secrets where name = p_name limit 1);
end $$;
revoke execute on function public.rg_secret(text) from public, anon, authenticated;
grant execute on function public.rg_secret(text) to service_role;

-- Secrets setup generates itself (webhook signing secret, SIP trunk password).
create or replace function public.rg_secret_put(p_name text, p_value text)
returns void language plpgsql security definer set search_path = public, vault as $$
declare v_id uuid;
begin
  if p_name not in ('elevenlabs_webhook_secret', 'telnyx_sip_password') then raise exception 'rg_secret_put: % not allowed', p_name; end if;
  select id into v_id from vault.secrets where name = p_name;
  if v_id is null then
    perform vault.create_secret(p_value, p_name, 'RoofGuard caller: generated by setup');
  else
    perform vault.update_secret(v_id, p_value);
  end if;
end $$;
revoke execute on function public.rg_secret_put(text, text) from public, anon, authenticated;
grant execute on function public.rg_secret_put(text, text) to service_role;

-- The two keys Jared pastes on /admin/roofguard.
create or replace function public.rg_key_put(p_name text, p_value text)
returns timestamptz language plpgsql security definer set search_path = public, vault as $$
declare v_id uuid;
begin
  if not public.has_role(auth.uid(), 'admin') then raise exception 'Admins only'; end if;
  if p_name not in ('elevenlabs_api_key', 'telnyx_api_key') then raise exception 'Not a RoofGuard key: %', p_name; end if;
  p_value := btrim(p_value);
  if coalesce(length(p_value), 0) < 8 or length(p_value) > 500 then raise exception 'That does not look like a key'; end if;
  select id into v_id from vault.secrets where name = p_name;
  if v_id is null then
    perform vault.create_secret(p_value, p_name, 'RoofGuard caller key (added from /admin/roofguard)');
  else
    perform vault.update_secret(v_id, p_value);
  end if;
  return now();
end $$;
revoke execute on function public.rg_key_put(text, text) from public, anon;
grant execute on function public.rg_key_put(text, text) to authenticated;

create or replace function public.rg_secret_status()
returns jsonb language plpgsql stable security definer set search_path = public, vault as $$
begin
  if not (public.has_role(auth.uid(), 'admin') or auth.role() = 'service_role') then raise exception 'admin only'; end if;
  return (select jsonb_object_agg(n, exists (select 1 from vault.secrets s where s.name = n))
            from unnest(array['elevenlabs_api_key','telnyx_api_key','elevenlabs_webhook_secret']) n);
end $$;
